CREATE TABLE IF NOT EXISTS registros (
  id SERIAL PRIMARY KEY,
  nombreCompleto TEXT NOT NULL,
  numeroEmergencia TEXT NOT NULL,
  fechaNacimiento TEXT,
  edad INTEGER,
  asociacion TEXT NOT NULL,
  club TEXT NOT NULL,
  tipoSangre TEXT,
  ta TEXT,
  fc TEXT,
  fr TEXT,
  temp TEXT,
  glucosa TEXT,
  spo2 TEXT,
  sintomas TEXT,
  eventoPrevio TEXT,
  antecedentes TEXT,
  medicamentos TEXT,
  alergias TEXT,
  tx TEXT,
  indicaciones TEXT,
  medico TEXT,
  requiereAmbulancia BOOLEAN DEFAULT FALSE,
  observacionTraslado TEXT,
  hospitalDestino TEXT,
  motivoTraslado TEXT,
  paramedico TEXT,
  firmaMedico TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
